package manager

import (
	"path/filepath"
	"strings"
	"testing"
)

func TestPackageJSONDeps(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, filepath.Join(dir, "package.json"), `{
  "name": "x",
  "dependencies": {"react": "^18.2.0", "@types/node": "^20.0.0"},
  "devDependencies": {"vitest": "^1.0.0"}
}`)
	es := collect(t, PackageJSONDeps{}, dir)
	got := map[string]string{}
	gotName := map[string]string{}
	for _, e := range es {
		got[e.Type] = e.Version
		gotName[e.Type] = e.Name
	}
	want := map[string]string{
		"npm:react":       "^18.2.0",
		"npm:@types/node": "^20.0.0",
		"npm:vitest":      "^1.0.0",
	}
	for k, v := range want {
		if got[k] != v {
			t.Errorf("%s: got %q, want %q", k, got[k], v)
		}
	}
	if gotName["npm:react"] != "package.json" {
		t.Errorf("prod dep Name: got %q, want %q", gotName["npm:react"], "package.json")
	}
	if gotName["npm:vitest"] != "package.json (dev)" {
		t.Errorf("dev dep Name: got %q, want %q", gotName["npm:vitest"], "package.json (dev)")
	}
}

func TestPackageLockJSON_V3(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, filepath.Join(dir, "package-lock.json"), `{
  "name": "x",
  "lockfileVersion": 3,
  "packages": {
    "": {
      "dependencies": {"react": "^18.2.0"},
      "devDependencies": {"vitest": "^1.0.0"}
    },
    "node_modules/react": {"version": "18.3.1"},
    "node_modules/vitest": {"version": "1.2.0", "dev": true},
    "node_modules/transitive": {"version": "9.9.9"}
  }
}`)
	es := collect(t, PackageLockJSON{}, dir)
	got := map[string]string{}
	gotName := map[string]string{}
	for _, e := range es {
		got[e.Type] = e.Version
		gotName[e.Type] = e.Name
	}
	if got["npm:react"] != "18.3.1" {
		t.Errorf("react: got %q, want 18.3.1", got["npm:react"])
	}
	if got["npm:vitest"] != "1.2.0" {
		t.Errorf("vitest: got %q, want 1.2.0", got["npm:vitest"])
	}
	// Transitive deps are emitted too: the lockfile pins what's actually
	// installed, which is what you want for vulnerability hunting.
	if got["npm:transitive"] != "9.9.9" {
		t.Errorf("transitive dep should be included, got %v", got)
	}
	if gotName["npm:react"] != "package-lock.json" {
		t.Errorf("prod dep Name: got %q", gotName["npm:react"])
	}
	if gotName["npm:vitest"] != "package-lock.json (dev)" {
		t.Errorf("dev dep Name: got %q", gotName["npm:vitest"])
	}
}

// V1 lockfiles (npm 5/6) store the hoisted tree under top-level "dependencies".
// We emit every entry (direct + hoisted transitive), consistent with the v2/v3
// path and the other lockfile managers. The "dev" flag drives the FILE column.
func TestPackageLockJSON_V1(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, filepath.Join(dir, "package-lock.json"), `{
  "name": "x",
  "lockfileVersion": 1,
  "dependencies": {
    "react": {"version": "18.3.1"},
    "vitest": {"version": "1.2.0", "dev": true},
    "transitive": {"version": "9.9.9"}
  }
}`)
	es := collect(t, PackageLockJSON{}, dir)
	got := map[string]string{}
	gotName := map[string]string{}
	for _, e := range es {
		got[e.Type] = e.Version
		gotName[e.Type] = e.Name
	}
	want := map[string]string{
		"npm:react":      "18.3.1",
		"npm:vitest":     "1.2.0",
		"npm:transitive": "9.9.9",
	}
	for k, v := range want {
		if got[k] != v {
			t.Errorf("%s: got %q, want %q", k, got[k], v)
		}
	}
	if gotName["npm:react"] != "package-lock.json" {
		t.Errorf("prod dep Name: got %q", gotName["npm:react"])
	}
	if gotName["npm:vitest"] != "package-lock.json (dev)" {
		t.Errorf("dev dep Name: got %q", gotName["npm:vitest"])
	}
}

func TestYarnLock(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, filepath.Join(dir, "yarn.lock"), `# THIS IS AN AUTOGENERATED FILE
# yarn lockfile v1


"react@^18.2.0":
  version "18.3.1"
  resolved "https://..."

"@types/node@^20.0.0", "@types/node@^20.10.0":
  version "20.11.5"

vitest@^1.0.0:
  version "1.2.0"

"forked-dep@git+ssh://git@github.com/x/y.git#abc":
  version "1.2.3"
`)
	es := collect(t, YarnLock{}, dir)
	got := map[string]string{}
	for _, e := range es {
		got[e.Type] = e.Version
	}
	want := map[string]string{
		"npm:react":       "18.3.1",
		"npm:@types/node": "20.11.5",
		"npm:vitest":      "1.2.0",
	}
	for k, v := range want {
		if got[k] != v {
			t.Errorf("%s: got %q, want %q", k, got[k], v)
		}
	}
	// URL specs split incorrectly with LastIndex('@'); don't emit garbage.
	for k := range got {
		if strings.Contains(k, "://") || strings.Contains(k, "git+") {
			t.Errorf("URL spec leaked through: %q", k)
		}
	}
}

// TestYarnLock_Berry covers Yarn v2+ (Berry) lockfiles, whose `version:` lines
// use a colon and unquoted value, and whose keys use the `@npm:` protocol. The
// leading `__metadata` block (with its own `version:`) must not be mistaken for
// a package.
func TestYarnLock_Berry(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, filepath.Join(dir, "yarn.lock"), `# This file is generated by running "yarn install"

__metadata:
  version: 8
  cacheKey: 10c0

"react@npm:^18.2.0":
  version: 18.3.1
  resolution: "react@npm:18.3.1"

"@types/node@npm:^20.0.0, @types/node@npm:^20.10.0":
  version: "20.11.5"
  resolution: "@types/node@npm:20.11.5"

"forked@npm:git+ssh://git@github.com/x/y.git#abc":
  version: 1.2.3
`)
	es := collect(t, YarnLock{}, dir)
	got := map[string]string{}
	for _, e := range es {
		got[e.Type] = e.Version
	}
	want := map[string]string{
		"npm:react":       "18.3.1",
		"npm:@types/node": "20.11.5",
	}
	for k, v := range want {
		if got[k] != v {
			t.Errorf("%s: got %q, want %q", k, got[k], v)
		}
	}
	if _, ok := got["npm:__metadata"]; ok {
		t.Errorf("__metadata block leaked through as a package: %v", got)
	}
	for k := range got {
		if strings.Contains(k, "://") || strings.Contains(k, "git+") {
			t.Errorf("URL spec leaked through: %q", k)
		}
	}
}

func TestPnpmLock(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, filepath.Join(dir, "pnpm-lock.yaml"), `
lockfileVersion: '9.0'
importers:
  .:
    dependencies:
      react:
        specifier: ^18.2.0
        version: 18.3.1
    devDependencies:
      vitest:
        specifier: ^1.0.0
        version: 1.2.0(react@18.3.1)
`)
	es := collect(t, PnpmLock{}, dir)
	got := map[string]string{}
	gotName := map[string]string{}
	for _, e := range es {
		got[e.Type] = e.Version
		gotName[e.Type] = e.Name
	}
	want := map[string]string{
		"npm:react":  "18.3.1",
		"npm:vitest": "1.2.0",
	}
	for k, v := range want {
		if got[k] != v {
			t.Errorf("%s: got %q, want %q", k, got[k], v)
		}
	}
	if gotName["npm:react"] != "pnpm-lock.yaml" {
		t.Errorf("prod dep Name: got %q", gotName["npm:react"])
	}
	if gotName["npm:vitest"] != "pnpm-lock.yaml (dev)" {
		t.Errorf("dev dep Name: got %q", gotName["npm:vitest"])
	}
}

func TestBunLock(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, filepath.Join(dir, "bun.lock"), `{
  "lockfileVersion": 1,
  "workspaces": {
    "": { "name": "my-app", "dependencies": ["bar@^1.0.0"] }
  },
  "packages": {
    "react": ["react@18.3.1", {}, "sha512-..."],
    "@types/node": ["@types/node@20.11.5", {}, "sha512-..."],
    "forked": ["forked@git+ssh://git@github.com/x/y.git#abc", {}]
  }
}`)
	es := collect(t, BunLock{}, dir)
	got := map[string]string{}
	for _, e := range es {
		got[e.Type] = e.Version
	}
	want := map[string]string{
		"npm:react":       "18.3.1",
		"npm:@types/node": "20.11.5",
	}
	for k, v := range want {
		if got[k] != v {
			t.Errorf("%s: got %q, want %q", k, got[k], v)
		}
	}
	for k, v := range got {
		if strings.Contains(k, "://") || strings.Contains(k, "git+") {
			t.Errorf("URL spec leaked through as type: %q", k)
		}
		if strings.Contains(v, "://") || strings.Contains(v, "git+") || strings.Contains(v, "github.com") {
			t.Errorf("URL spec leaked through as version: %s = %q", k, v)
		}
	}
	if _, ok := got["npm:forked"]; ok {
		t.Errorf("URL-based dep `forked` should be skipped, got %v", got)
	}
	if _, ok := got["npm:my-app"]; ok {
		t.Errorf("workspace name should not be parsed as a dependency")
	}
}
